version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5050:5050'
    depends_on:
      - mongo
    environment:
      - PORT=5050
      - MONGO_URI=mongodb://mongo:27017/ticketing
      - JWT_SECRET=verysecretkey
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:
